---
concurrency:
  cancel-in-progress: true
  group: '${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}'
jobs:
  tests:
    name: 'Tests'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y extra-cmake-modules lcov libavcodec-dev libavformat-dev libavutil-dev libsoundtouch-dev
      - name: Install Qt
        uses: jurplel/install-qt-action@a9c63c7c123f3069cff414e7e482d95dfa9d8125
        with:
          modules: qtmultimedia
      - env:
          BUILD_TYPE: '${{ matrix.build-type }}'
        name: Configure
        run: >-
          cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" -B "${GITHUB_WORKSPACE}"/build
          --install-prefix "${GITHUB_WORKSPACE}"/build/prefix
          -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
          -DBUILD_TESTS=ON
          -DCOVERAGE=ON
          -DFHS=ON
      - env:
          BUILD_TYPE: '${{ matrix.build-type }}'
        name: Build
        run: cmake --build "${GITHUB_WORKSPACE}"/build --verbose --config "${BUILD_TYPE}"
      - env:
          BUILD_TYPE: '${{ matrix.build-type }}'
        name: Install
        run: cmake --install "${GITHUB_WORKSPACE}"/build --config "${BUILD_TYPE}" --verbose
      - name: Run tests
        run: ctest --test-dir "${GITHUB_WORKSPACE}"/build/tests
        env:
          QT_QPA_PLATFORM: offscreen
          QT_QUICK_BACKEND: software
      - if: ${{ matrix.build-type == 'Debug' }}
        name: Generate coverage information
        run: >-
          lcov -c -d "${GITHUB_WORKSPACE}"/build -o coverage1.lcov
          --exclude build
          --omit-lines '^\}$'
          --exclude tests
          --include src
          --keep-going
      - if: ${{ matrix.build-type == 'Debug' }}
        name: Coveralls
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]
name: Tests
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
permissions:
  contents: 'read'
